name: biogest_clinic_movile
description: 'Mobile application developed in Flutter for users of associated clinics, enabling seamless communication and comprehensive management of their activities. Users can chat with each other, receive and view notifications, view their appointment calendar, and access various administrative features related to their clinic. The main objective of the application is to improve user interaction, organization, and experience by providing a modern, intuitive, and efficient platform.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^10.2.0
  flutter_neat_and_clean_calendar: ^0.4.16
  flutter_svg: ^2.2.1
  form_builder_validators: ^11.2.0
  get: ^4.7.2
  glass_kit: ^4.0.2
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  searchfield: ^1.3.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/icon/icon.png'
    background_color: '#FFFFFF'
    theme_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/icon/icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icon/icon.png'
